### ISSUE TITLE
Release new version with LDAP support

### ISSUE THREAD

**Issue by guenhter** [testcontainers/testcontainers-rs-modules-community#199]
### Feature request description

LDAP support was merged recently. It would be great to have a this available via crates.io

**Comment by DDtKey** [comment]
Hi 👋 
Yes, it will be released soon

**Comment by DDtKey** [comment]
It’s been released 🎉 
https://github.com/testcontainers/testcontainers-rs-modules-community/releases/tag/v0.10.0
