### ISSUE TITLE
Release 0.10.0 Request

### ISSUE THREAD

**Issue by mominul** [testcontainers/testcontainers-rs-modules-community#201]
### Feature request description

Requesting a new  version release targeting ` testcontainers` ` v0.22.0 `.

cc @DDtKey 

Thanks!

**Comment by DDtKey** [comment]
Thanks for raising the issue, I’ve prepared updated and forgot to publish, sorry

It’s been released 🎉 
https://github.com/testcontainers/testcontainers-rs-modules-community/releases/tag/v0.10.0

**Comment by mominul** [comment]
Thanks a lot! ❤️
