### ISSUE TITLE
[feat] Add support for Databend

### ISSUE THREAD

**Issue by hantmac** [testcontainers/testcontainers-rs-modules-community#212]
### Feature request description

[Databend](https://github.com/datafuselabs/databend), built in Rust, is an open-source cloud data warehouse, we can support it in testcontainers-rs.

**Comment by Anju023** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive
