### ISSUE TITLE
Redis Stack support

### ISSUE THREAD

**Issue by tsurai** [testcontainers/testcontainers-rs-modules-community#95]
### Feature request description

I would like to add the `Redis Stack` image to use the various `JSON` commands in `Redis`. Would you rather have me add a second `RedisStack` struct in the same `redis` module or add it as a separate module?

### Image reference

`redis/redis-stack-server`

**Comment by DDtKey** [comment]
Hi @tsurai!
I don't mind to add `Redis Stack` to existing `redis` module, but need to split them into two separate files. And in order not to cause breaking changes, we should re-export them through existing `mod.rs`
